# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Nagini Tests (All) Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      BOOGIE_EXE: "/home/runner/.dotnet/tools/boogie"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Boogie
      run: |
        dotnet tool install --global Boogie --version 2.15.9
    - name: Install Nagini
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Run Nagini tests
      run: |
        chmod +x ./public/scripts/test-all.sh
        ./public/scripts/test-all.sh
      shell: bash
        # nagini 000-has-close-elements.py