# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Nagini Tests Ubuntu

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      BOOGIE_EXE: "/home/runner/.dotnet/tools/boogie"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Boogie
      run: |
        dotnet tool install --global Boogie --version 2.15.9
    - name: Install Nagini
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
    - name: Run Nagini tests
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        chmod +x ./public/scripts/test-new.sh
        ./public/scripts/test.sh-new $ALL_CHANGED_FILES
      shell: bash
        # nagini 000-has-close-elements.py